### ISSUE TITLE
잘못된 @downloadURL 및 @updateURL

### ISSUE THREAD

**Issue by rishubil** [Shinjjanggu/jakhonplus#1]
https://github.com/Shinjjanggu/jakhonplus/blob/69bafbde7404915944e06c1fbc4476883b645b5b/jakhonhangle_jp.user.js#L11-L12

위 두 줄의 URL 값을 https://shinjjanggu.github.io/jakhonplus/jakhonhangle_jp.user.js 으로 변경해야 합니다.

현재 URL은 글로벌 서버용 업데이트 URL로, 주기적으로 Tempermonkey가 유저스크립트를 업데이트 시도할 경우,
일본 서버용 스크립트가 글로벌 서버용 스크립트로 덮어씌워질 수 있습니다.

**Comment by Shinjjanggu** [comment]
수정완료! 바꾼다는 게 깜빡햇서요 ㄳㄳ

**Comment by rishubil** [comment]
https://openuserjs.org/ 쪽 말고 github쪽도 수정해주셔야 합니다.

**Comment by Shinjjanggu** [comment]
수정완료! ㄳㄳ

**Comment by rishubil** [comment]
수정 확인했습니다. 감사합니다.
